### ISSUE TITLE
Debian console, apt-get update problems

### ISSUE THREAD

**Issue by zimme** [rancher/os#931]
**RancherOS Version: 0.4.4** @ **docker-machine**

Trying to run an upgrade on the debian-console results in error because of `/sbin/poweroff` being a mountpoint and can't be hardlinked during upgrade.

``` sh
sudo apt-get update; sudo apt-get upgrade;
...
Preparing to unpack .../systemd-sysv_215-17+deb8u4_amd64.deb ...
Unpacking systemd-sysv (215-17+deb8u4) over (215-17+deb8u3) ...
dpkg: error processing archive /var/cache/apt/archives/systemd-sysv_215-17+deb8u4_amd64.deb (--unpack):
 unable to make backup link of './sbin/poweroff' before installing new version: Invalid cross-device link
Errors were encountered while processing:
 /var/cache/apt/archives/systemd-sysv_215-17+deb8u4_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by deniseschannon** [comment]
I was unable to reproduce with v0.4.5-rc2

**Comment by zimme** [comment]
I'll try that version too, to confirm.

**Comment by zimme** [comment]
Tried with version `0.4.5-rc2`. With this version using `docker-machine`, I can't even get it to start `debian-console`.

```sh
[docker@RancherOS ~]$ sudo ros service list
disabled amazon-ecs-agent
disabled centos-console
enabled  debian-console
disabled fedora-console
disabled kernel-headers
disabled kernel-headers-system-docker
disabled resize-fs
disabled ubuntu-console
```
```sh
[docker@RancherOS ~]$ sudo system-docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS               NAMES
8d6929543730        rancher/os-docker:v0.4.5-rc2    "/usr/sbin/entry.sh /"   15 hours ago        Up 13 hours                             docker
650b48c81934        rancher/os-console:v0.4.5-rc2   "/usr/sbin/entry.sh /"   15 hours ago        Up 13 hours                             console
8ef69361ce01        rancher/os-network:v0.4.5-rc2   "/usr/sbin/entry.sh /"   15 hours ago        Up 13 hours                             network
dbc15604965f        rancher/os-ntp:v0.4.5-rc2       "/usr/sbin/entry.sh /"   15 hours ago        Up 13 hours                             ntp
c3423794aa0f        rancher/os-udev:v0.4.5-rc2      "/usr/sbin/entry.sh /"   15 hours ago        Up 13 hours                             udev
45484dcb2b88        rancher/os-acpid:v0.4.5-rc2     "/usr/sbin/entry.sh /"   15 hours ago        Up 13 hours                             acpid
2aca413ed2c8        rancher/os-syslog:v0.4.5-rc2    "/usr/sbin/entry.sh /"   15 hours ago        Up 13 hours                             syslog
```

**Comment by deniseschannon** [comment]
What version of docker-machine are you using? I'm using `docker-machine version 0.6.0, build e27fb87`.

Did you reboot after enabling the system service? 

```
docker@rc2testagain:~$ sudo ros service list
disabled amazon-ecs-agent
disabled centos-console
enabled  debian-console
disabled fedora-console
disabled kernel-headers
disabled kernel-headers-system-docker
disabled resize-fs
disabled ubuntu-console
docker@rc2testagain:~$ sudo system-docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS               NAMES
769401717df3        rancher/os-debianconsole:v0.4.5-rc2   "/usr/sbin/entry.sh /"   55 seconds ago      Up 54 seconds                           console
e0b2ed090c8c        rancher/os-docker:v0.4.5-rc2          "/usr/sbin/entry.sh /"   3 minutes ago       Up 54 seconds                           docker
f0e9bb41d64f        rancher/os-network:v0.4.5-rc2         "/usr/sbin/entry.sh /"   3 minutes ago       Up 55 seconds                           network
e731a1e3ab14        rancher/os-ntp:v0.4.5-rc2             "/usr/sbin/entry.sh /"   3 minutes ago       Up 58 seconds                           ntp
e29339d13ed9        rancher/os-udev:v0.4.5-rc2            "/usr/sbin/entry.sh /"   3 minutes ago       Up 59 seconds                           udev
4985a83d3b63        rancher/os-syslog:v0.4.5-rc2          "/usr/sbin/entry.sh /"   3 minutes ago       Up About a minute                       syslog
0d3dd4b8f23f        rancher/os-acpid:v0.4.5-rc2           "/usr/sbin/entry.sh /"   3 minutes ago       Up About a minute                       acpid
docker@rc2testagain:~$ docker@rc2testagain:~$
```

**Comment by zimme** [comment]
Sorry for the delay, I'm on `docker-machine version 0.7.0, build a650a40`.

I've rebooted several times after doing `sudo ros s enable debian-console`.

**Comment by zimme** [comment]
But maybe we're getting off-topic here, maybe I should open a new issue for this?

**Comment by zimme** [comment]
So I've installed `RancherOS@0.4.5` to disk on a bare-metal x86_64 machine.

I've changed into a `debian-console`, and when I try and upgrade debian to stretch I run into the same problem with `systemd-sysv` failing to installed because it can't link `./sbin/shutdown`.

```sh
The following extra packages will be installed:
  systemd-sysv
The following packages will be upgraded:
  systemd-sysv
1 upgraded, 0 newly installed, 0 to remove and 70 not upgraded.
8 not fully installed or removed.
Need to get 63.8 kB of archives.
After this operation, 11.3 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://httpredir.debian.org/debian/ stretch/main systemd-sysv amd64 229-5 [63.8 kB]
Fetched 63.8 kB in 1s (41.4 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 11130 files and directories currently installed.)
Preparing to unpack .../systemd-sysv_229-5_amd64.deb ...
Unpacking systemd-sysv (229-5) over (215-17+deb8u4) ...
dpkg: error processing archive /var/cache/apt/archives/systemd-sysv_229-5_amd64.deb (--unpack):
 unable to make backup link of './sbin/shutdown' before installing new version: Invalid cross-device link
Errors were encountered while processing:
 /var/cache/apt/archives/systemd-sysv_229-5_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
So I was thinking, maybe a "better" alternative to removing and mounting `shutdown`/`poweroff`/etc. is to not remove the binaries from the default install and instead just use `/usr/local/sbin` for the mount points of `poweroff`/`shutdown`/etc. and add `/usr/locale/sbin:/usr/sbin:/sbin` to the path.

Hopefully this could prevent update problems of the console os because the binaries should be there and linkable and such.

**Comment by peron** [comment]
The issue is still there with the latest release on Raspberry and the Ubuntu console:

> rancher@rancher:~$ uname -a
> Linux rancher 4.1.17-hypriotos-v7+ #2 SMP PREEMPT Fri Feb 12 08:10:38 UTC 2016 armv7l armv7l armv7l GNU/Linux
> rancher@rancher:~$ sudo ros --version
> ros version v0.6.1
> rancher@rancher:~$ sudo ros console list
> disabled centos
> disabled debian
> disabled default
> disabled fedora
> current  ubuntu
> disabled xfce
> rancher@rancher:~$ sudo apt-get upgrade
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Calculating upgrade... Done
> The following packages will be upgraded:
>   libp11-kit0 libssl1.0.0 libudev1 openssl systemd-sysv
> 5 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Need to get 1'353 kB of archives.
> After this operation, 61.4 kB disk space will be freed.
> Do you want to continue? [Y/n] 
> Get:1 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main armhf systemd-sysv armhf 229-4ubuntu8 [13.8 kB]
> Get:2 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main armhf libudev1 armhf 229-4ubuntu8 [51.2 kB]
> Get:3 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main armhf libp11-kit0 armhf 0.23.2-5~ubuntu16.04.1 [91.0 kB]
> Get:4 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main armhf libssl1.0.0 armhf 1.0.2g-1ubuntu4.4 [712 kB]
> Get:5 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main armhf openssl armhf 1.0.2g-1ubuntu4.4 [485 kB]
> Fetched 1'353 kB in 0s (1'435 kB/s)
> debconf: delaying package configuration, since apt-utils is not installed
> (Reading database ... 18202 files and directories currently installed.)
> Preparing to unpack .../systemd-sysv_229-4ubuntu8_armhf.deb ...
> Unpacking systemd-sysv (229-4ubuntu8) over (229-4ubuntu7) ...
> dpkg: error processing archive /var/cache/apt/archives/systemd-sysv_229-4ubuntu8_armhf.deb (--unpack):
>  unable to make backup link of './sbin/poweroff' before installing new version: Invalid cross-device link
> Errors were encountered while processing:
>  /var/cache/apt/archives/systemd-sysv_229-4ubuntu8_armhf.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> rancher@rancher:~$ 
>

**Comment by SvenDowideit** [comment]
I feel weird about the idea that you're running `apt-get upgrade` on a container - but IDK what the right way to do things in RancherOS is yet.

**Comment by 2devnull** [comment]
getting this too on recent upgrade from 0.4.4 to 0.6.1

**Comment by tailtwo** [comment]
Same problem (0.6.1 with Debian console).

```
Preparing to unpack .../systemd-sysv_215-17+deb8u5_amd64.deb ...
Unpacking systemd-sysv (215-17+deb8u5) over (215-17+deb8u4) ...
dpkg: error processing archive /var/cache/apt/archives/systemd-sysv_215-17+deb8u5_amd64.deb (--unpack):
 unable to make backup link of `./sbin/poweroff' before installing new version: Invalid cross-device link
Errors were encountered while processing:
 /var/cache/apt/archives/systemd-sysv_215-17+deb8u5_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by zimme** [comment]
Upgraded debian jessie to stretch without problems during the upgrade process.
One thing to note though, the upgrade process hardlinks a few commands like `reboot`/`poweroff`/`shutdown` so after the upgrade process I had to use `sudo ros entrypoint reboot` to reboot the server.

But I still feel this is resolved so I'm closing this.

**Comment by 2devnull** [comment]
Can you say how to resolve this? I'm on the latest version 1.1.3 and still getting this upgrade error.

**Comment by zimme** [comment]
For me, this was resolved with the PR's that changed bind mounts to synlinks on poweroff/reboot/shutdown. So I don't know rancheros is back to using bind mounts for this or if there's some update some other place that is causing this.

I do believe you should open a new issue to track your errors for this, even though they are similar to what I reported, it might be because of something else and it deserves its own issue.

**Comment by 2devnull** [comment]
I am sure it is probably fixed now if I were to create a new ubuntu console. However, I have an older container of the ubuntu console I would like to keep current and was hoping there is a way to fix that. Too many things go wrong when a new console is used.

**Comment by zimme** [comment]
@2devnull Would you be able to mount a volume into the console container and "save" your home folder etc. and after that upgrade to a new console container and mount the same volume into that new console contianer?

**Comment by 2devnull** [comment]
so, that is interesting....I am not sure it is only the home folder that gets destroyed. On a pre-1.0 version a couple years ago when the ros upgrade also blew away the consolve container, I believe more than just home folder was gone. It would be good (at least for me to understand) how this console container is linked. I also believe all the apt-get packages are gone too, so more than just personal files.
